Add stylesheet optimizations for smaller viewports
chichi-berlin/website pull request #22
Opened 2024-07-07 10:05 UTC by o1y

This PR adds mobile styles for the chi-chi website.

* I have integrated optimizations for smaller viewports (smartphones). It is possible that some layout shifts may still occur on very exotic viewport sizes.

* To get the project running on my arm64 workstation, I have added an optional Docker image. The project can be started as a developer using `docker compose up`. This image is not intended for production use.

* Furthermore, I have fixed a bug where the slick carousels were not rendering correctly. In the current devel branch, version 1.8.1 has been locked, which is not compatible with the current stylesheets, so I downgraded slick-carousel to 1.7.1.

Feel free to test and nitpick. If any errors come up or if you see more requirements for style improvements, let me know :)

2026-01-05 13:47 UTC, lucendio requested changes
Went through the commit history and left some comments. Let me know, if you'd like to have a chat and go through them.

2026-01-05 13:47 UTC, lucendio commented on docker-compose.yml
why is there a compose file needed, when the difference is literally an npm sub-command?

2026-01-05 13:47 UTC, lucendio commented on .babelrc
> +                "regenerator": true
will this change to the opposite value have an impact?

2026-01-05 13:47 UTC, lucendio commented on .webpack.config
pls check redundant comments in this file (added by genAI).

also, is the second line in this file still valid since you refactored the approach?

2026-01-05 13:47 UTC, lucendio commented on config.yml
> +# Markup configuration (replaces deprecated blackfriday and pygments settings)
already mentioned in commit msg

2026-01-05 13:47 UTC, lucendio commented on config.yml
> -preserveTaxonomyNames:      false
what is replacing this? (I tried to find some info but there doesnt seem to be a way to search through Hugo's release notes, at least I did not find any)

2026-01-05 13:47 UTC, lucendio commented on .webpack.config
> +                                    encodeEntity: (char) => char  // Don't encode entities
```suggestion
                                    // NOTE: disable default character encoding and use characters *as-is*
                                    encodeEntity: (char) => char
```
or add a note in the commit msg instead.

2026-01-05 13:47 UTC, lucendio commented on config.yml
> -    dir: ':resourceDir'
what are the replacements for these configuration attributes?

2026-01-05 13:47 UTC, lucendio commented on app/layouts/_default/baseof.html
> +        {{ end }}
wrong indentation

```suggestion
            {{ $sectionPath := trim .Dir "/" }}
            {{ $node := $.Site.GetPage "section" $sectionPath }}
            {{ with $node }}
                {{ $.Scratch.Set "pageName" $node.Params.section }}    
                {{ $.Scratch.Set "pageName" $node.Params.section }}
            {{ end }}
```

2026-01-05 13:47 UTC, lucendio commented on package.json
> -    "watch:hugo": "HUGO_ENV='development' hugo serve --bind 0.0.0.0 --port 3000 --noHTTPCache --i18n-warnings",
is there some sort of replacement for this? as it helps to uncover cases when reserved keywords are being used.

2026-01-05 13:47 UTC, lucendio commented on app/layouts/rubric/single.html
> +        <span class="value">{{ $value }}</span>
this one is a misleading diff as the branch bodies have been swapped

2026-01-05 13:47 UTC, lucendio commented on Dockerfile
> +FROM node:20-slim
pls use a fully qualified image name (including registry).

2026-01-05 13:47 UTC, lucendio commented on package.json
> +    "watch:hugo": "HUGO_ENV='development' hugo serve --bind 0.0.0.0 --port 3000 --noHTTPCache --poll 700ms",
duplicated map key

2026-01-05 13:47 UTC, lucendio commented on .gitignore
> +.claude/
-.-

2026-01-05 13:47 UTC, lucendio commented on eslint.config.js
that looks like significant less rules compared to before. got some of them lost along the way?

2026-01-05 13:47 UTC, lucendio commented on build/scss-glob-loader.cjs
> +async function processGlobs(source, fileDir, loaderContext) {
should be placed before `exports`, or exports should be placed at the bottom.

2026-01-05 13:47 UTC, lucendio commented on app/js/lib/side-menu.js
> +            var menu_id = menuEl.getAttribute( 'data-menu' );
camel vs snake syntax mix - should be camel everywhere.

2026-01-05 13:47 UTC, lucendio commented on app/js/lib/side-menu.js
> +                parseInt( pos *
that was on purpose.

2026-01-05 13:47 UTC, lucendio commented on app/js/lib/side-menu.js
> +            while( (siblingNode = bc.nextSibling) ){
an assignment? here? this should be a (type safe) comparison, no?

2026-01-05 13:47 UTC, lucendio commented on app/js/etc/tracking.js
referring to the entire commit here: some of the fixes really make sense (e.g. quoting, or indentation), others IMHO not so much (e.g. fixing upstream lib copies, or var name underscore prefixing). I think it makes more sense to keep the former and disable the latter, to prevent unnecessary noise.

2026-01-05 13:47 UTC, lucendio commented on app/layouts/partials/head/csp.html
> +        script-src 'self' https://siteconnect.wertgarantie-services.de {{ $trackingURL.Scheme }}://{{ $trackingURL.Host }} {{ if eq (getenv "HUGO_ENV") "development" }}'unsafe-inline' 'unsafe-eval'{{
would be helpful if the commit message states, why

2026-01-05 13:47 UTC, lucendio commented on app/js/main/initializations.js
>          });
```suggestion
        this.addEventListener( 'click', function( event ){
            event.preventDefault();
            const { site } = global;
            const { dataset } = site;

            dataset.state_header_menu = dataset.state_header_menu === 'open' ? 'closed' : 'open';
            button.setAttribute( 'aria-expanded', dataset.state_header_menu === 'closed' );
        });
```

2026-01-05 13:47 UTC, lucendio commented on app/js/main/initializations.js
>          });
readability will IMHO no be increased. line length is debatable, though, true.

2026-01-05 13:47 UTC, lucendio commented on app/styling/layouts/master.scss
> -            hyphens: auto;
why was this done again?

would it make sense, instead of manually add `&shy;`, add it during build time? meaning, pre-process all `title` values by analyzing their natural (orthography) break points and inject `&shy;` to all of them?

2026-01-05 13:47 UTC, lucendio commented on app/js/main/initializations.js
> +            }, 500);
was the delay of `200` not enough?

2026-01-05 13:47 UTC, lucendio commented on app/js/main/initializations.js
> +            } else if (!event.target.closest('a')) {
this looks funky

2026-01-05 13:47 UTC, lucendio commented on app/js/main/initializations.js
> +        const isMobile = window.matchMedia('(max-width: 1023px)');
```suggestion
        const isMobile = window.matchMedia('(max-width: 1023px)').matches;
```
and down below only use `isMobile` as `matches` is boolean type

2026-01-05 13:47 UTC, lucendio commented on app/layouts/partials/components/aside.scss
> +    height: 100dvh;
duplicate attribute

2026-01-05 13:47 UTC, lucendio commented on app/js/main/initializations.js
> +        // Remove inline styles added by slick that break centering
could be moved to commit message

2026-01-05 14:26 UTC, o1y commented on app/layouts/partials/components/aside.scss
> +    height: 100dvh;
This is an intentional `height` fallback for the `dvh` value, which is not supported across all browsers.

2026-01-05 14:44 UTC, o1y commented on config.yml
> -preserveTaxonomyNames:      false
`preserveTaxonomyNames` is deprecated. The default was `false`, so there _should_ be no replacement required.

2026-01-05 14:58 UTC, o1y commented on app/styling/layouts/master.scss
> -            hyphens: auto;
This change was requested by you because line breaks should be controlled manually instead of automatically. Some of the previous auto line breaks were not ideal based on the initial feedback.

2026-02-24 01:33 UTC, lucendio commented
The commit history of this PR was carefully reviewed and almost every commit was cherry-picked into the default branch, either as-is or if need be, amended or slightly modified. The result can be found in [this diff](https://github.com/chichi-berlin/website/compare/53128d6399ebd773959d8dff84b377aa1e8de1bf...5e0e8b80427978c95450894815758b7eeab8fe2e).

Thank you for all your hard work and effort you put into this. This was much appreciated and truly helpful!

2026-02-24 01:33 UTC, closed without merging